[package]
name = "veccentric"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
overload = "0.1"
rand = { version = "0.8", features = ["small_rng"], optional = true }

[features]
random = ["rand"]
